const imageValue = document.querySelector('.first-image');
const temperature = document.querySelector('.temp-value-celsius');
const humidityValue = document.querySelector('.humidity-value');
const precipitationValue = document.querySelector('.precipitation-value');
const hrsMin = document.querySelector('.hrs-mins');
const second = document.querySelector('.seconds');
const dateClass = document.querySelector('.date');
const amImage = document.querySelector('.am-image');
const farenheitValue = document.querySelector('.temp-value-farenheit');
const tempHourly = document.querySelectorAll('.temperature-hourly-update');
const hourly = document.querySelectorAll('.hourly-image');
const firstContainer = document.querySelector('.first-container');
const index = document.querySelector('.option-click');
export { imageValue, firstContainer, temperature, tempHourly, index, hourly, humidityValue, precipitationValue, hrsMin, second, dateClass, amImage, farenheitValue };
